steps:
  # Step 1: Create Instance Template
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-templates
      - create
      - ipv4-v6-template-$BUILD_ID
      - --machine-type=e2-micro
      - --image-family=debian-12
      - --image-project=debian-cloud
      - --tags=allow-http,allow-https,allow-ssh,ipv4-v6
      - --metadata=startup-script=
          #!/bin/bash
          apt-get update -y
          apt-get install nginx -y
          systemctl enable nginx
          systemctl start nginx
          echo "Hi all! Hope you had a great session on Dual VPC, IPv4 & IPv6 Load Balancers!" > /var/www/html/index.nginx-debian.html

  # Step 2: Update the MIG to use the new template
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-groups
      - managed
      - set-instance-template
      - ipv4-v6-mig
      - --template=ipv4-v6-template-$BUILD_ID
      - --region=asia-south1

  # Step 3: Rolling restart to apply the new template
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - ipv4-v6-mig
      - --version=template=ipv4-v6-template-$BUILD_ID
      - --region=asia-south1

options:
  logging: CLOUD_LOGGING_ONLY
