steps:
  # Step 1: Create instance template
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-templates
      - create
      - ipv4-v6-template-fixed
      - --machine-type=e2-micro
      - --image-family=debian-12
      - --image-project=debian-cloud
      - --tags=allow-http,allow-https,allow-ssh,ipv4-v6
      - --metadata=startup-script=#!/bin/bash
        apt-get update -y
        apt-get install nginx -y
        systemctl enable nginx
        systemctl start nginx
        echo "Hi all! Hope you had a great session on Dual VPC, IPv4 & IPv6 Load Balancers!" > /var/www/html/index.nginx-debian.html

  # Step 2: Update MIG to use the new template
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-groups
      - managed
      - set-instance-template
      - ipv4-v6-mig
      - --template=ipv4-v6-template-fixed
      - --zone=asia-south1-a

  # Step 3: Recreate all instances in MIG
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-groups
      - managed
      - recreate-instances
      - ipv4-v6-mig
      - --instances=ipv4-v6-mig
      - --zone=asia-south1-a

options:
  logging: CLOUD_LOGGING_ONLY
