steps:
# Create new instance template with timestamped name and use startup.sh for metadata
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      TEMPLATE_NAME="ipv4-v6-template-$(date +%Y%m%d%H%M%S)"
      PROJECT_ID="training-2024-batch"

      echo "Creating new template: $$TEMPLATE_NAME"
      gcloud compute instance-templates create $$TEMPLATE_NAME \
        --machine-type=e2-micro \
        --image-family=debian-12 \
        --image-project=debian-cloud \
        --subnet=ipv4-v6-subnet \
        --region=asia-south1 \
        --stack-type=IPV4_IPV6 \
        --network-tier=PREMIUM \
        --tags=allow-http,allow-https,allow-ssh,ipv4-v6 \
        --metadata-from-file=startup-script=startup.sh \
        --project=$$PROJECT_ID

      echo $$TEMPLATE_NAME > template_name.txt

# Update MIG to use new template
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      TEMPLATE_NAME=$$(cat template_name.txt)
      PROJECT_ID="training-2024-batch"
      echo "Updating MIG to use template: $$TEMPLATE_NAME"
      gcloud compute instance-groups managed set-instance-template ipv4-v6-mig \
        --region=asia-south1 \
        --template=$$TEMPLATE_NAME \
        --project=$$PROJECT_ID

# Trigger rolling update for MIG to replace instances one by one
- name: gcr.io/cloud-builders/gcloud
  args:
    - compute
    - instance-groups
    - managed
    - rolling-action
    - start-update
    - ipv4-v6-mig
    - --region=asia-south1
    - --type=proactive
    - --max-unavailable=1
    - --project=training-2024-batch

options:
  logging: CLOUD_LOGGING_ONLY
